title: Input Icons Documentation
description: Documentation for Input Icons for Input System
theme: just-the-docs
color_scheme: dark

url: https://github.com/TobiFroi/input-icons-documentation

aux_links:
  "Input Icons on Asset Store":
    - "https://assetstore.unity.com/packages/tools/gui/input-icons-for-input-system-213736"

# Makes Aux links open in a new tab
aux_links_new_tab: true
